# Generated by Django 6.1 on 2026-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tech_used', models.CharField(help_text='Example: Python, Django, HTML, CSS', max_length=200)),
                ('github_link', models.URLField(blank=True, help_text='Link to the GitHub repo for this project (optional)', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Optional screenshot of the project', null=True, upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
